#!/usr/bin/env sh
set -eu

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

printf '%s\n' 'Running go test -race -coverprofile=coverage.out ./...'
go test -race -coverprofile=coverage.out ./...
go tool cover -func=coverage.out
