aliases:
    - alias: r/{subreddit}
      destination: https://www.reddit.com/r/{subreddit}
    - alias: gh/{owner}/{name}
      destination: https://github.com/{owner}/{name}
    - alias: wiki/{topic}
      destination: https://en.wikipedia.org/wiki/{topic}
    - alias: yt/{}
      destination: https://www.youtube.com/results?search_query={}
    - alias: t/{user}
      destination: https://x.com/{user}
    - alias: gh
      destination: https://github.com
      enabled: true
    - alias: g
      destination: https://www.google.com
    - alias: jay
      destination: https://jayovalle.com
    - alias: jpmc
      destination: https://jpmorganchase.com
    - alias: todo
      destination: https://app.todoist.com/app/
    - alias: yc
      destination: https://news.ycombinator.com
links:
    g: https://www.google.com
    gh: https://github.com
    jay: https://jayovalle.com
    jpmc: https://jpmorganchase.com
    todo: https://app.todoist.com/app/
    yc: https://news.ycombinator.com
